name: Build and Release Mini Player

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt6 dependencies
        run: sudo apt-get update && sudo apt-get install -y qt6-base-dev qt6-base-dev-tools

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Set script permissions
        run: chmod +x bump_version_and_tag.sh

      - name: Bump version and tag
        run: ./bump_version_and_tag.sh

      - name: Build with PyInstaller
        run: |
          pyinstaller app.spec

      - name: Archive build output
        run: |
          cd dist
          zip -r MiniPlayer.zip MiniPlayer
        shell: bash

      - name: Get version
        id: get_version
        run: |
          VERSION=$(python -c "import importlib.util; spec = importlib.util.spec_from_file_location('miniplayer', 'src/miniplayer/__init__.py'); miniplayer = importlib.util.module_from_spec(spec); spec.loader.exec_module(miniplayer); print(getattr(miniplayer, '__version__', '0.0.0'))")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Mini Player v${{ steps.get_version.outputs.version }}
          body: 'Automated release from main branch.'
          files: dist/MiniPlayer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
